"""initial foundation schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-19

Hand-written (not autogenerated) so column types, constraints, indexes,
and the immutable-vs-timestamped split are explicit and reviewable, per
the DeepSeek V4 review (section 9.3).

Tables created in dependency order:

1.  inboxes                  — durable mailbox source identity
2.  inbox_cursor_history     — append-only cursor advance audit
3.  source_messages          — fetched messages, dedup on (inbox, uidvalidity, uid)
4.  message_content_metadata — 1:1 parsed headers (PII-scoped)
5.  processing_attempts      — append-only LLM extraction attempts
6.  transaction_candidates   — structured candidates derived from attempts
7.  review_tasks             — 1:1 review work items
8.  review_decisions         — append-only reviewer decisions
9.  import_commands          — import commands (mutable status; transition
                                history lives in audit_events)
10. wallet_attempts          — append-only Wallet API submission attempts
11. wallet_receipts           — provider confirmations (1:1 with commands)
12. audit_events             — cross-cutting append-only audit log

UUIDs are PostgreSQL ``uuid`` generated client-side by the ORM.
Timestamps are ``TIMESTAMPTZ`` (timezone-aware) and default to ``now()``.
Money is integer minor units (``BIGINT``) plus a 3-char ISO 4217 currency.

Immutability for the five append-only tables
(``processing_attempts``, ``inbox_cursor_history``, ``review_decisions``,
``wallet_attempts``, ``audit_events``) is enforced by ``BEFORE UPDATE OR
DELETE`` triggers that raise an exception. The absence of ``updated_at``
on those tables is a secondary signal; the trigger is the authoritative
guard. ``import_commands`` is intentionally mutable: it stores the
*current* status of the command, and the full transition history is
preserved in ``audit_events``.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid() -> sa.types.TypeEngine:
    return postgresql.UUID(as_uuid=True)


def _ts() -> sa.types.TypeEngine:
    return sa.DateTime(timezone=True)


def _jsonb() -> sa.types.TypeEngine:
    return postgresql.JSONB()


# Tables that are append-only: a BEFORE UPDATE OR DELETE trigger
# raises an exception so the table cannot be mutated after insert.
_APPEND_ONLY_TABLES = (
    "processing_attempts",
    "inbox_cursor_history",
    "review_decisions",
    "wallet_attempts",
    "audit_events",
)


def _create_append_only_trigger(table_name: str) -> None:
    """Install a BEFORE UPDATE OR DELETE trigger that rejects mutations.

    The trigger raises PostgreSQL's user-defined ``P0001`` SQLSTATE, with
    ``append_only_violation`` in the message, so the error is identifiable
    in logs and application exception handling. The function is created
    per-table to keep the migration self-contained and to make ``DROP`` in
    ``downgrade`` symmetric.
    """

    func_name = f"enforce_append_only_{table_name}"
    trigger_name = f"tr_append_only_{table_name}"
    op.execute(
        sa.text(
            f"""
            CREATE OR REPLACE FUNCTION {func_name}()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION
                    'table {table_name} is append-only: UPDATE and DELETE are forbidden'
                    USING ERRCODE = 'P0001';
            END;
            $$ LANGUAGE plpgsql;
            """
        )
    )
    op.execute(
        sa.text(
            f"""
            CREATE TRIGGER {trigger_name}
                BEFORE UPDATE OR DELETE ON {table_name}
                FOR EACH ROW
                EXECUTE FUNCTION {func_name}();
            """
        )
    )


def _drop_append_only_trigger(table_name: str) -> None:
    func_name = f"enforce_append_only_{table_name}"
    trigger_name = f"tr_append_only_{table_name}"
    op.execute(sa.text(f"DROP TRIGGER IF EXISTS {trigger_name} ON {table_name};"))
    op.execute(sa.text(f"DROP FUNCTION IF EXISTS {func_name}();"))


def upgrade() -> None:
    # 1. inboxes -----------------------------------------------------------
    op.create_table(
        "inboxes",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column(
            "account_fingerprint", sa.String(length=64), nullable=False
        ),
        sa.Column("folder", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("uid_validity", sa.BigInteger(), nullable=True),
        sa.Column("last_seen_uid", sa.BigInteger(), nullable=True),
        sa.Column(
            "last_observed_at", _ts(), nullable=True
        ),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "length(provider) >= 1",
            name="ck_inboxes_provider_nonempty",
        ),
        sa.CheckConstraint(
            "length(account_fingerprint) = 64",
            name="ck_inboxes_fingerprint_len",
        ),
        sa.CheckConstraint(
            "(uid_validity IS NULL AND last_seen_uid IS NULL) "
            "OR (uid_validity IS NOT NULL AND last_seen_uid IS NOT NULL)",
            name="ck_inboxes_cursor_pair",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'drained', 'revoked')",
            name="ck_inboxes_status",
        ),
        sa.UniqueConstraint(
            "provider",
            "account_fingerprint",
            "folder",
            name="uq_inboxes_provider_account_folder",
        ),
    )
    op.create_index(
        "ix_inboxes_status", "inboxes", ["status"]
    )

    # 2. inbox_cursor_history (append-only) -------------------------------
    op.create_table(
        "inbox_cursor_history",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column(
            "inbox_id",
            _uuid(),
            sa.ForeignKey("inboxes.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("uid_validity", sa.BigInteger(), nullable=False),
        sa.Column("last_seen_uid", sa.BigInteger(), nullable=False),
        sa.Column("observed_at", _ts(), nullable=False),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "uid_validity >= 1",
            name="ck_inbox_cursor_history_uid_validity",
        ),
        sa.CheckConstraint(
            "last_seen_uid >= 1",
            name="ck_inbox_cursor_history_last_seen_uid",
        ),
    )
    op.create_index(
        "ix_inbox_cursor_history_inbox_observed",
        "inbox_cursor_history",
        ["inbox_id", "observed_at"],
    )

    # 3. source_messages ---------------------------------------------------
    op.create_table(
        "source_messages",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column(
            "inbox_id",
            _uuid(),
            sa.ForeignKey("inboxes.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("uid_validity", sa.BigInteger(), nullable=False),
        sa.Column("message_uid", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("received_at", _ts(), nullable=False),
        sa.Column("retain_until", _ts(), nullable=True),
        sa.Column("purged_at", _ts(), nullable=True),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "uid_validity >= 1", name="ck_source_messages_uid_validity"
        ),
        sa.CheckConstraint(
            "message_uid >= 1", name="ck_source_messages_message_uid"
        ),
        sa.CheckConstraint(
            "char_length(content_hash) >= 32",
            name="ck_source_messages_content_hash_len",
        ),
        sa.UniqueConstraint(
            "inbox_id",
            "uid_validity",
            "message_uid",
            name="uq_source_messages_inbox_uidvalidity_uid",
        ),
    )
    op.create_index(
        "ix_source_messages_inbox_status",
        "source_messages",
        ["inbox_id", "status", "received_at"],
    )

    # 4. message_content_metadata -----------------------------------------
    op.create_table(
        "message_content_metadata",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column(
            "source_message_id",
            _uuid(),
            sa.ForeignKey("source_messages.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("sender", sa.String(length=512), nullable=True),
        sa.Column("recipient", sa.String(length=512), nullable=True),
        sa.Column("subject", sa.String(length=1024), nullable=True),
        sa.Column(
            "message_id_header", sa.String(length=512), nullable=True
        ),
        sa.Column("sent_at", _ts(), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=True),
        sa.Column("merchant_name", sa.String(length=255), nullable=True),
        sa.Column("retain_until", _ts(), nullable=True),
        sa.Column("purged_at", _ts(), nullable=True),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint(
            "source_message_id",
            name="uq_message_content_metadata_one",
        ),
    )

    # 5. processing_attempts (append-only: no updated_at) -----------------
    op.create_table(
        "processing_attempts",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column(
            "source_message_id",
            _uuid(),
            sa.ForeignKey("source_messages.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("attempt_index", sa.Integer(), nullable=False),
        sa.Column(
            "idempotency_key", sa.String(length=128), nullable=False
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=True),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("raw_response", _jsonb(), nullable=True),
        sa.Column("structured_output", _jsonb(), nullable=True),
        sa.Column("error_kind", sa.String(length=64), nullable=True),
        sa.Column(
            "error_message", sa.String(length=2048), nullable=True
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("token_usage", _jsonb(), nullable=True),
        sa.Column("retain_until", _ts(), nullable=True),
        sa.Column("purged_at", _ts(), nullable=True),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "attempt_index >= 1", name="ck_attempts_index_positive"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'succeeded', 'failed', "
            "'invalid_output', 'schema_violation')",
            name="ck_attempts_status",
        ),
        sa.UniqueConstraint(
            "source_message_id",
            "attempt_index",
            name="uq_attempts_source_message_index",
        ),
        sa.UniqueConstraint(
            "idempotency_key", name="uq_attempts_idempotency_key"
        ),
    )
    op.create_index(
        "ix_processing_attempts_source_message_status",
        "processing_attempts",
        ["source_message_id", "status"],
    )

    # 6. transaction_candidates -------------------------------------------
    op.create_table(
        "transaction_candidates",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column(
            "source_message_id",
            _uuid(),
            sa.ForeignKey("source_messages.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "attempt_id",
            _uuid(),
            sa.ForeignKey("processing_attempts.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column(
            "previous_candidate_id",
            _uuid(),
            sa.ForeignKey(
                "transaction_candidates.id", ondelete="SET NULL"
            ),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("merchant", sa.String(length=255), nullable=True),
        sa.Column("reference", sa.String(length=255), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=True),
        sa.Column("structured_payload", _jsonb(), nullable=True),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "amount_minor > 0", name="ck_candidates_amount_positive"
        ),
        sa.CheckConstraint(
            "length(currency) = 3 "
            "AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' "
            "AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' "
            "AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'",
            name="ck_candidates_currency_format",
        ),
        sa.CheckConstraint(
            "candidate_version >= 1",
            name="ck_candidates_version_positive",
        ),
        sa.UniqueConstraint(
            "source_message_id",
            "candidate_version",
            name="uq_candidates_source_message_version",
        ),
    )
    op.create_index(
        "ix_transaction_candidates_status",
        "transaction_candidates",
        ["status"],
    )

    # 7. review_tasks ------------------------------------------------------
    op.create_table(
        "review_tasks",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column(
            "candidate_id",
            _uuid(),
            sa.ForeignKey(
                "transaction_candidates.id", ondelete="RESTRICT"
            ),
            nullable=False,
        ),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "state IN ('open', 'decided', 'superseded')",
            name="ck_review_tasks_state",
        ),
        sa.UniqueConstraint(
            "candidate_id", name="uq_review_tasks_candidate_one"
        ),
    )

    # 8. review_decisions (append-only: no updated_at) -------------------
    op.create_table(
        "review_decisions",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column(
            "review_task_id",
            _uuid(),
            sa.ForeignKey("review_tasks.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "candidate_id",
            _uuid(),
            sa.ForeignKey(
                "transaction_candidates.id", ondelete="RESTRICT"
            ),
            nullable=False,
        ),
        sa.Column("reviewer_id", sa.String(length=128), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("decided_at", _ts(), nullable=False),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected', 'deferred')",
            name="ck_review_decisions_decision",
        ),
    )
    op.create_index(
        "ix_review_decisions_task_decided",
        "review_decisions",
        ["review_task_id", "decided_at"],
    )

    # 9. import_commands (mutable: Timestamped, carries updated_at) ------
    op.create_table(
        "import_commands",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column(
            "candidate_id",
            _uuid(),
            sa.ForeignKey(
                "transaction_candidates.id", ondelete="RESTRICT"
            ),
            nullable=False,
        ),
        sa.Column(
            "idempotency_key", sa.String(length=128), nullable=False
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payload", _jsonb(), nullable=False),
        sa.Column("issued_at", _ts(), nullable=False),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'in_flight', 'succeeded', "
            "'failed', 'unknown', 'reconciled')",
            name="ck_import_commands_status",
        ),
        sa.CheckConstraint(
            "length(idempotency_key) >= 16",
            name="ck_import_commands_idempotency_key_len",
        ),
        sa.UniqueConstraint(
            "candidate_id", name="uq_import_commands_candidate_one"
        ),
        sa.UniqueConstraint(
            "idempotency_key", name="uq_import_commands_idempotency_key"
        ),
    )
    op.create_index(
        "ix_import_commands_status",
        "import_commands",
        ["status"],
    )

    # 10. wallet_attempts (append-only: no updated_at) -------------------
    op.create_table(
        "wallet_attempts",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column(
            "import_command_id",
            _uuid(),
            sa.ForeignKey("import_commands.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("attempt_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provider_request", _jsonb(), nullable=True),
        sa.Column("provider_response", _jsonb(), nullable=True),
        sa.Column("error_kind", sa.String(length=64), nullable=True),
        sa.Column(
            "error_message", sa.String(length=2048), nullable=True
        ),
        sa.Column("submitted_at", _ts(), nullable=True),
        sa.Column("acknowledged_at", _ts(), nullable=True),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "attempt_index >= 1", name="ck_wallet_attempts_index"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'submitted', 'acknowledged', "
            "'failed', 'unknown', 'reconciled')",
            name="ck_wallet_attempts_status",
        ),
        sa.UniqueConstraint(
            "import_command_id",
            "attempt_index",
            name="uq_wallet_attempts_command_index",
        ),
    )
    op.create_index(
        "ix_wallet_attempts_command_status",
        "wallet_attempts",
        ["import_command_id", "status"],
    )

    # 11. wallet_receipts -------------------------------------------------
    op.create_table(
        "wallet_receipts",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column(
            "import_command_id",
            _uuid(),
            sa.ForeignKey("import_commands.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "wallet_attempt_id",
            _uuid(),
            sa.ForeignKey("wallet_attempts.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column(
            "provider_transaction_id",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "reconciliation_status", sa.String(length=16), nullable=False
        ),
        sa.Column(
            "confirmed_amount_minor", sa.BigInteger(), nullable=True
        ),
        sa.Column(
            "confirmed_currency", sa.String(length=3), nullable=True
        ),
        sa.Column("received_at", _ts(), nullable=False),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "confirmed_amount_minor IS NULL "
            "OR confirmed_amount_minor >= 0",
            name="ck_wallet_receipts_amount_nonnegative",
        ),
        sa.CheckConstraint(
            "confirmed_currency IS NULL OR "
            "(length(confirmed_currency) = 3 "
            "AND substr(confirmed_currency, 1, 1) BETWEEN 'A' AND 'Z' "
            "AND substr(confirmed_currency, 2, 1) BETWEEN 'A' AND 'Z' "
            "AND substr(confirmed_currency, 3, 1) BETWEEN 'A' AND 'Z')",
            name="ck_wallet_receipts_currency_format",
        ),
        sa.CheckConstraint(
            "reconciliation_status IN ('matched', 'mismatch', 'pending')",
            name="ck_wallet_receipts_reconciliation_status",
        ),
        sa.UniqueConstraint(
            "import_command_id", name="uq_wallet_receipts_command_one"
        ),
    )
    op.create_index(
        "ix_wallet_receipts_reconciliation_status",
        "wallet_receipts",
        ["reconciliation_status"],
    )

    # 12. audit_events (append-only: no updated_at) ----------------------
    op.create_table(
        "audit_events",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("entity_kind", sa.String(length=32), nullable=False),
        sa.Column("entity_id", _uuid(), nullable=False),
        sa.Column("event_kind", sa.String(length=48), nullable=False),
        sa.Column("payload", _jsonb(), nullable=True),
        sa.Column("occurred_at", _ts(), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            _ts(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index(
        "ix_audit_events_entity",
        "audit_events",
        ["entity_kind", "entity_id", "occurred_at"],
    )
    op.create_index(
        "ix_audit_events_event_kind",
        "audit_events",
        ["event_kind"],
    )

    # --- Immutability triggers -------------------------------------------
    # Append-only enforcement for the five immutable tables. The trigger
    # raises on UPDATE or DELETE so the immutability invariant is
    # enforced by the database, not by the absence of a column.
    for table_name in _APPEND_ONLY_TABLES:
        _create_append_only_trigger(table_name)


def downgrade() -> None:
    for table_name in _APPEND_ONLY_TABLES:
        _drop_append_only_trigger(table_name)

    op.drop_table("audit_events")
    op.drop_index(
        "ix_wallet_receipts_reconciliation_status",
        table_name="wallet_receipts",
    )
    op.drop_table("wallet_receipts")
    op.drop_index(
        "ix_wallet_attempts_command_status", table_name="wallet_attempts"
    )
    op.drop_table("wallet_attempts")
    op.drop_index(
        "ix_import_commands_status", table_name="import_commands"
    )
    op.drop_table("import_commands")
    op.drop_index(
        "ix_review_decisions_task_decided", table_name="review_decisions"
    )
    op.drop_table("review_decisions")
    op.drop_table("review_tasks")
    op.drop_index(
        "ix_transaction_candidates_status",
        table_name="transaction_candidates",
    )
    op.drop_table("transaction_candidates")
    op.drop_index(
        "ix_processing_attempts_source_message_status",
        table_name="processing_attempts",
    )
    op.drop_table("processing_attempts")
    op.drop_table("message_content_metadata")
    op.drop_index(
        "ix_source_messages_inbox_status", table_name="source_messages"
    )
    op.drop_table("source_messages")
    op.drop_index(
        "ix_inbox_cursor_history_inbox_observed",
        table_name="inbox_cursor_history",
    )
    op.drop_table("inbox_cursor_history")
    op.drop_index("ix_inboxes_status", table_name="inboxes")
    op.drop_table("inboxes")
